# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 20

[[main]]
  name = "Members"
  url = "/members"
  weight = 30

[[main]]
  name = "Publications"
  url = "/publications"
  weight = 40

[[main]]
  name = "Projects"
  url = "/Projects"
  weight = 50

[[main]]
  name = "Talks"
  url = "/talks"
  weight = 65

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70


# [[main]]
#   name = "国内镜像"
#   url = "https://zjuvag.gitee.io/"
#   weight = 65

# [[main]]
#   name = "International Access"
#   url = "https://zjuvag.org/"
#   weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
